import * as vscode from 'vscode';
import * as path from 'path';
import { DataProvider } from './data-provider';

const DICT_PATH = '.vibe/MODULE_DICT.md';

/**
 * Watches the DataProvider for changes and regenerates
 * the MODULE_DICT.md file that AI reads before assigning modules.
 */
export class ModuleDict {
  private dataProvider: DataProvider;
  private debounceTimer: ReturnType<typeof setTimeout> | null = null;
  private disposables: vscode.Disposable[] = [];

  constructor(dataProvider: DataProvider) {
    this.dataProvider = dataProvider;
  }

  initialize(): void {
    // Listen for data changes and regenerate dict
    this.disposables.push(
      this.dataProvider.onDidChange(() => {
        this.scheduleRegenerate();
      })
    );

    // Generate initial dict
    this.regenerate();
  }

  dispose(): void {
    this.disposables.forEach(d => d.dispose());
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }
  }

  // ── internal ────────────────────────────────────────

  private scheduleRegenerate(): void {
    if (this.debounceTimer) {
      clearTimeout(this.debounceTimer);
    }
    // Debounce 500ms to avoid excessive writes during batch operations
    this.debounceTimer = setTimeout(() => {
      this.regenerate();
    }, 500);
  }

  private async regenerate(): Promise<void> {
    const root = this.dataProvider.getWorkspaceRoot();
    if (!root) { return; }

    const modules = this.dataProvider.getModules();
    if (modules.length === 0) { return; }

    const lines: string[] = [
      '# VibeTrace Module Dictionary',
      '',
      '> Auto-generated by VibeTrace. Do not edit manually — changes will be overwritten.',
      '',
      'When assigning a `module` for a new event, you **MUST** read this file first.',
      '',
      '## Rules',
      '',
      '1. If the current work matches an existing module below, use that **exact** name.',
      '2. If no module matches, you may create a new one using short CamelCase (e.g. `UserProfile`, `PaymentGateway`).',
      '3. Do **NOT** create variants of existing modules (e.g. if `Auth` exists, do not use `Authentication`).',
      '',
      '## Existing Modules',
      '',
    ];

    for (const moduleName of modules) {
      // Collect sample intents to describe the module
      const events = this.dataProvider.getByModule(moduleName);
      const sampleIntent = events[0]?.intent ?? 'No description available';
      // Truncate long intents for readability
      const shortDesc = sampleIntent.length > 80
        ? sampleIntent.slice(0, 80) + '...'
        : sampleIntent;
      lines.push(`- **${moduleName}** — ${shortDesc}`);
    }

    lines.push('');

    const dictUri = vscode.Uri.file(path.join(root, DICT_PATH));
    const content = Buffer.from(lines.join('\n'), 'utf-8');

    try {
      await vscode.workspace.fs.writeFile(dictUri, content);
    } catch {
      // Silently fail — directory might not exist yet (AI creates it)
    }
  }
}
